// bmg_front_react/src/components/ConfirmModal.tsx
import React from 'react';
import './ConfirmModal.css';

export type ConfirmModalType = 'confirmar' | 'perigo';

interface ConfirmModalProps {
  titulo?: string;
  mensagem: string;
  labelConfirmar?: string;
  labelCancelar?: string;
  tipo?: ConfirmModalType;
  onConfirmar: () => void;
  onCancelar: () => void;
}

export const ConfirmModal: React.FC<ConfirmModalProps> = ({
  titulo = 'Confirmar',
  mensagem,
  labelConfirmar = 'Confirmar',
  labelCancelar = 'Cancelar',
  tipo = 'confirmar',
  onConfirmar,
  onCancelar,
}) => {
  return (
    <div className="modal-overlay" onClick={onCancelar}>
      <div
        className="modal-box"
        role="dialog"
        aria-modal="true"
        aria-label={titulo}
        onClick={(e) => e.stopPropagation()}
      >
        <h3 className="modal-title">{titulo}</h3>
        <p className="modal-message">{mensagem}</p>
        <div className="modal-actions">
          <button
            type="button"
            className="btn-modal btn-cancelar"
            onClick={onCancelar}
          >
            {labelCancelar}
          </button>
          <button
            type="button"
            className={`btn-modal btn-confirmar${
              tipo === 'perigo' ? ' perigo' : ''
            }`}
            onClick={onConfirmar}
          >
            {labelConfirmar}
          </button>
        </div>
      </div>
    </div>
  );
};

// BMG_Front/src/app/shared/confirm-modal/confirm-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-confirm-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './confirm-modal.component.html',
  styleUrls: ['./confirm-modal.component.scss']
})
export class ConfirmModalComponent {
  @Input() titulo = 'Confirmar';
  @Input() mensagem = '';
  @Input() labelConfirmar = 'Confirmar';
  @Input() labelCancelar = 'Cancelar';
  @Input() tipo: 'confirmar' | 'perigo' = 'confirmar';

  @Output() confirmar = new EventEmitter<void>();
  @Output() cancelar = new EventEmitter<void>();

  onConfirmar(): void {
    this.confirmar.emit();
  }

  onCancelar(): void {
    this.cancelar.emit();
  }
}

<div class="modal-overlay" (click)="onCancelar()">
  <div class="modal-box" (click)="$event.stopPropagation()" role="dialog" aria-modal="true" [attr.aria-label]="titulo">
    <h3 class="modal-title">{{ titulo }}</h3>
    <p class="modal-message">{{ mensagem }}</p>
    <div class="modal-actions">
      <button type="button" class="btn-modal btn-cancelar" (click)="onCancelar()">{{ labelCancelar }}</button>
      <button type="button" class="btn-modal btn-confirmar" [class.perigo]="tipo === 'perigo'" (click)="onConfirmar()">{{ labelConfirmar }}</button>
    </div>
  </div>
</div>
